version: 2.1

orbs:
  architect: giantswarm/architect@4.28.0

workflows:
  version: 2

  build_and_update:
    jobs:
      - architect/push-to-docker:
          context: architect
          name: "build"
          image: "quay.io/giantswarm/handbook"
          username_envar: "QUAY_USERNAME"
          password_envar: "QUAY_PASSWORD"
          dockerfile: "./Dockerfile"
          tag-latest-branch: "main"
          filters:
            # Trigger job also on git tag.
            tags:
              only: /^v.*/
      - architect/push-to-app-catalog:
          context: architect
          name: push-to-app-catalog
          executor: architect
          app_catalog: "giantswarm-operations-platform-catalog"
          app_catalog_test: "giantswarm-operations-platform-test-catalog"
          chart: handbook
          filters:
            # Trigger job also on git tag.
            tags:
              only: /^v.*/
