{{ $this := . }}
{{ range $index, $secret := .Values.secrets }}
apiVersion: v1
kind: Secret
{{- if eq (index $secret.data 0).key ".dockerconfigjson" }}
type: kubernetes.io/dockerconfigjson
{{- else }}
type: Opaque
{{- end }}
metadata:
  name: {{ $secret.name }}
  namespace: {{ include "resource.default.namespace" $this }}
  labels:
    {{- include "labels.common" $this | nindent 4 }}
data:
  {{- range $idx, $datum := $secret.data }}
  {{ $datum.key }}: {{ $datum.value }}
  {{- end }}
---
{{ end }}
