staticJsCmsHugoStandaloneVersion: v0.0.1

secrets:
  # Information for staticjscms-hugo-standalone and its OAuth proxy component
  - name: staticjscms-secret
    data:
      - key: ORIGINS
        value: aHR0cHM6Ly9oYW5kYm9vay5naWFudHN3YXJtLmlv
      - key: OAUTH_CLIENT_ID
        value: MjE5OTEyMzk5MWFzZGVhZGJlZWY=
      - key: OAUTH_CLIENT_SECRET
        value: YWFkc3NhZGFkYWRhZGFkMTIzMTIzMTIzMWFkYWRhZDEyMzEyM2FiYw==
      - key: GIT_HOSTNAME
        value: ""
  - name: staticjscms-hugo-standalone-pull-secret
    data:
      - key: .dockerconfigjson
        value: ewogICAgICAgICAgICAiYXV0aHMiOiB7CiAgICAgICAgICAgICAgImdoY3IuaW8iOiB7CiAgICAgICAgICAgICAgICAiYXV0aCI6ICJZbXhoWW14aE9tSnNZV0pzWVFvPSIKICAgICAgICAgICAgICB9CiAgICAgICAgICAgIH0KICAgICAgICAgIH0=
